module.exports = {
    APP_SERVER_ERR: -1,
    TEST: 0,
    TEMP_FILE_SAVE_ERR: 1,
    WRONG_FILE_TYPE_UPLOADED_ERR: 2,
    TEMP_FILE_UNLINK_ERR: 3,
    TEMP_FILE_STAT_ERR:4,
    TEMP_FILE_PATH_NOT_FOUND_ERR: 5,
    TEMP_FILE_DIGESTION_ERR: 6,
    QUERY_ERR: 7,
    QUESTION_NOT_FOUND_ERR: 8,
    DATA_NOT_AVAILABLE_ERR: 9,
    USER_SEARCH_ERR: 10
}